## Tipos de estadística

La estadística se divide en dos grandes ramas:

<div class="card-stack">

<div class="card fragment fade-up evolucion-card" data-fragment-index="1"
     style="background:#f8fafc; border:1px solid #e5e7eb; border-top: 6px solid #60a5fa; border-radius: 22px; padding: 26px 28px; box-shadow: 0 8px 22px rgba(0,0,0,0.05);">

<h4 class="mb-16" style="font-size: 1.35em;">Estadística descriptiva</h4>

<p class="fragment fade-in text-justify" style="font-size: 30px;" data-fragment-index="1">
La estadística descriptiva es la rama de la estadística que se encarga de **organizar**, **resumir** y **presentar datos**, utilizando **tablas**, **gráficos** y medidas numéricas como la **media**, **mediana**, **moda**, **varianza** y **desviación estándar**, con el fin de describir sus características sin realizar generalizaciones.
</p>

<ul class="text-justify" style="font-size: 30px;">
<li class="fragment fade-up" data-fragment-index="2">
**Ejemplo:** promedio de notas, histogramas, tablas de frecuencia.
</li>
</ul> 

</div>

<div class="card fragment fade-up evolucion-card" data-fragment-index="3"
     style="background:#f8fafc; border:1px solid #e5e7eb; border-top: 6px solid #60a5fa; border-radius: 22px; padding: 26px 28px; box-shadow: 0 8px 22px rgba(0,0,0,0.08);">

<h4 class="mb-16" style="font-size: 1.35em;">Estadística inferencial</h4>
<p class="fragment fade-in text-justify" style="font-size: 30px;" data-fragment-index="3">
La estadística inferencial es la rama de la estadística que permite obtener conclusiones y tomar decisiones sobre una población a partir de una muestra, mediante el uso de medidas como estimaciones, intervalos de confianza, pruebas de hipótesis y modelos probabilísticos.
</p>

<ul class="text-justify" style="font-size: 30px;">
<li class="fragment fade-up" data-fragment-index="4">
Estimar el promedio de estudiantes de toda una universidad.
</li>
<li class="fragment fade-up" data-fragment-index="5">  
Evaluar si un medicamento es efectivo.  
</li>
<li class="fragment fade-up" data-fragment-index="6">  
Realizar una prueba de hipótesis. 
</li>
</ul> 

</div>

</div>

