## Ejemplo: Errores en una prueba de hipótesis

<div style="background-color:#eef4fb;
padding:18px;
border-radius:18px;
border-top:8px solid #1a3a6b;">

<div style="font-size:30px;
text-align:justify;
line-height:1.2;">
Un investigador desea evaluar si un nuevo suplemento aumenta el productividad promedio de un rebaño caprino.
</div>
<ul style="padding-left:30px; margin-top:10px;font-size:30px;">
<li>$H_0$: El suplemento no aumenta el productividad.</li>
<li>$H_1$: El suplemento aumenta el productividad.</li>
</ul>

</div>

<div style="display:grid;
grid-template-columns:1fr 1fr;
gap:18px;
margin-top:14px;">

<div class="fragment fade-up" data-fragment-index="1"
style="background-color:#fdecec;
padding:18px;
border-radius:18px;
border-top:8px solid #b91c1c;">

<div style="font-size:27px;
font-weight:bold;
text-align:center;
color:#b91c1c;">

Error Tipo I ($\alpha$)

</div>

<div style="font-size:26px;
text-align:justify;
line-height:1.2;">

Se concluye que el suplemento mejora el productividad y se rechaza $H_0$, cuando en realidad no produce ningún efecto. 
<br>
**Interpretación**: Se recomienda un suplemento que realmente no funciona. 

**Consecuencia**: pérdidas económicas para los productores.
</div>

</div>

<div class="fragment fade-up" data-fragment-index="2"
style="background-color:#fff7e8;
padding:18px;
border-radius:18px;
border-top:8px solid #d97706;">

<div style="font-size:27px;
font-weight:bold;
text-align:center;
color:#d97706;">

Error Tipo II ($\beta$)

</div>

<div style="font-size:26px;
text-align:justify;
line-height:1.2;">

Se concluye que el suplemento no mejora el productividad y no se rechaza $H_0$, cuando en realidad sí produce una mejora. 
<br>
**Interpretación**: Se descarta un suplemento que realmente sí funciona.  

**Consecuencia**: se pierde una oportunidad de aumentar la producción.
</div>

</div>

</div>

