## Estadístico de prueba y región de rechazo

<div style="font-size: 30px; text-align: justify; margin-top: 30px;">
En una prueba de hipótesis, la decisión estadística se fundamenta en el estadístico de prueba y en su comparación con la región de rechazo.
</div>
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-top: 15px;">

<div class="fragment fade-right" data-fragment-index="1"
style="background-color: #eef4fb; padding: 18px; border-radius: 16px; border-top: 8px solid #1a3a6b;">

<div style="font-size: 32px; font-weight: bold; color: #1a3a6b; text-align: center;">
Estadístico de prueba
</div>

<div style="font-size: 28px; margin-top: 12px; text-align: justify;">
Es una **medida calculada** a partir de los datos muestrales que **permite comparar** la información observada con lo planteado en la hipótesis nula.
</div>

<div style="font-size: 28px; margin-top: 10px; text-align: justify;">
Su valor indica qué tan alejados están los datos respecto al valor esperado bajo $H_0$, por ejemplo, $Z$ es un estadístico de prueba.
</div>

<div style="text-align: center; font-size: 26px;">
$$Z = \frac{\bar{x}-\mu_0}{\sigma/\sqrt{n}}$$
</div>
</div>

<div class="fragment fade-left" data-fragment-index="2"
style="background-color: #eef7ee; padding: 18px; border-radius: 16px; border-top: 8px solid #1b4d2e;">

<div style="font-size: 32px; font-weight: bold; color: #1b4d2e; text-align: center;">
Región de rechazo
</div>

<div class="block-body" style="text-align:justify;font-size: 28px; line-height: 1.6;">
Sea $C$ un **subconjunto del espacio muestral** tal que, de acuerdo con la prueba prescrita, nos **lleva al rechazo de la hipótesis nula**. Entonces $C$ es llamada la <strong>región crítica</strong> o <strong>región de rechazo</strong> de la prueba. $C^c$ es llamada la <strong>región de aceptación</strong> o <strong>región de no rechazo</strong>.

</div>

<div style="background-color: #d6f0dd; padding: 12px; border-radius: 12px; margin-top: 10px; font-size: 24px; text-align: justify; line-height: 1.6;">
Si $\mathbf{x} \in C$ → se rechaza $H_0$. &nbsp;&nbsp; Si $\mathbf{x} \in C^c$ → no se rechaza $H_0$.
</div>

</div>

</div>

