## Ejemplo 3: solución

<div class="twocol">

<div class="card fragment fade-up" data-fragment-index="1">
<ul>

<li class="fragment fade-up" data-fragment-index="2" style="font-size: 20px; text-align: justify;">
Tabla de frecuencias completa
</li>

<li class="fragment fade-up" data-fragment-index="3" style="font-size: 20px; text-align: justify;">
<table style="width: 90%; margin: auto; font-size: 18px;">

<thead>
<tr style="background-color: #2c3e50; color: white;">
<th>Intervalo</th>
<th>$x_i$</th>
<th>$f_i$</th>
<th>$(f_i\cdot x_i)$</th>
<th>$(x_i - \bar{x})$</th>
<th>$(x_i - \bar{x})^2$</th>
<th>$f_i\cdot (x_i - \bar{x})^2$</th>
</tr>
</thead>

<tbody>

<tr>
<td>10–19</td><td>14,5</td><td>5</td><td>72,5</td><td>-26,28</td><td>690,64</td><td>3.453,20</td>
</tr>

<tr style="background-color: #ecf0f1;">
<td>19–28</td><td>23,5</td><td>11</td><td>258,5</td><td>-17,28</td><td>298,60</td><td>3.284,60</td>
</tr>

<tr>
<td>28–37</td><td>32,5</td><td>8</td><td>260,0</td><td>-8,28</td><td>68,57</td><td>548,56</td>
</tr>

<tr style="background-color: #ecf0f1;">
<td>37–46</td><td>41,5</td><td>5</td><td>207,5</td><td>0,72</td><td>0,52</td><td>2,60</td>
</tr>

<tr>
<td>46–55</td><td>50,5</td><td>8</td><td>404,0</td><td>9,72</td><td>94,53</td><td>756,24</td>
</tr>

<tr style="background-color: #ecf0f1;">
<td>55–64</td><td>59,5</td><td>6</td><td>357,0</td><td>18,72</td><td>350,44</td><td>2.102,64</td>
</tr>

<tr>
<td>64–73</td><td>68,5</td><td>7</td><td>479,5</td><td>27,72</td><td>768,40</td><td>5.378,80</td>
</tr>

</tbody>

<tfoot>
<tr style="background-color: #34495e; color: white; font-weight: bold;">
<td>Total</td>
<td>-</td>
<td>50</td>
<td>2.039</td>
<td>-</td>
<td>-</td>
<td>15.526,64</td>
</tr>
</tfoot>

</table>
</li>

<li class="fragment fade-up" data-fragment-index="4" style="font-size: 20px; text-align: justify;">
Con la tabla de frecuencias se procede a hacer los cálculos.
</li>
<li class="fragment fade-in" data-fragment-index="5" style="font-size: 20px; text-align: justify;">
Media: $\bar{x}= \frac{\sum_{i=1}^{7}f_ix_i}{50}=\frac{2.039}{50}=40,78$
</li>

<li class="fragment fade-in" data-fragment-index="6" style="font-size: 20px; text-align: justify;">
El promedio de edad de la comunidad es aproximadamente 41 años.
</li>

<li class="fragment fade-in" data-fragment-index="7" style="font-size: 20px; text-align: justify;">
Varianza y desviación estándar muestral
</li>
<li class="fragment fade-in" data-fragment-index="8" style="font-size: 20px; text-align: justify;">
Para la varianza muestral aplicamos la siguiente fórmula:
</li>

<li class="fragment fade-in" data-fragment-index="9" style="font-size: 20px; text-align: justify;list-style: none;">
$s^2 = \frac{\sum_{i=1}^{k} f_i(x_i- \bar{x})^2}{n - 1}$
</li>




</ul>
</div>

<div class="card fragment fade-up" data-fragment-index="10">
<ul>

<li class="fragment fade-in" data-fragment-index="12" style="font-size: 20px; text-align: justify;list-style: none;">
$s^2 = \frac{\sum_{i=1}^{7} f_i(x_i- \bar{x})^2}{(50 - 1)}=\frac{15.526,64}{49}=316,87$
</li>
<li class="fragment fade-in" data-fragment-index="13" style="font-size: 20px; text-align: justify;">
Con la varianza se procede a hallar la desviación estándar.
</li>
<li class="fragment fade-in" data-fragment-index="14" style="font-size: 20px; text-align: justify;list-style: none;">
$s=\sqrt{s^2}=\sqrt{316,87}=17,8$
</li>

<li class="fragment fade-in" data-fragment-index="17" style="list-style: none;font-size: 20px; text-align: justify;">
Si los datos fueran poblacionales?
</li>
<li class="fragment fade-in" data-fragment-index="18" style="font-size: 20px; text-align: justify;">
Varianza Poblacional: se calcula con la siguiente fórmula:
</li>
<li class="fragment fade-in" data-fragment-index="19" style="font-size: 20px; text-align: justify;list-style: none;">
$\sigma^2 = \frac{\sum_{i=1}^{k} f_i(x_i- \bar{x})^2}{N}$
</li>
<li class="fragment fade-in" data-fragment-index="20" style="font-size: 20px; text-align: justify;">
Reemplazando con los datos de la tabla:
</li>
<li class="fragment fade-in" data-fragment-index="21" style="font-size: 20px; text-align: justify;list-style: none;">
$\sigma^2 = \frac{\sum_{i=1}^{7} f_i(x_i- \bar{x})^2}{50}=\frac{15.526,64}{50}=310,533$
</li>
<li class="fragment fade-in" data-fragment-index="22" style="font-size: 20px; text-align: justify;">
Con la varianza se calcula la desviación estándar
</li>
<li class="fragment fade-in" data-fragment-index="22" style="font-size: 20px; text-align: justify;list-style: none;">
$\sigma=\sqrt{\sigma^2}=\sqrt{310,533}=17,62$
</li>
</ul>
</div>

</div>

