## Ejercicio: germinación de semillas de trigo

<div class="twocol">

<div class="card fragment fade-up" data-fragment-index="1">
<ul>
<li class="fragment fade-up text-justify no-bullets" data-fragment-index="2" style="font-size: 26px;">
Se siembran 4 semillas de trigo de forma independiente. La probabilidad de germinación de cada semilla es $p = 0.75$.
</li>
<li class="fragment fade-up text-justify no-bullets" data-fragment-index="3" style="font-size: 26px;">
Calcule la probabilidad de que <strong>al menos una semilla germine</strong>.
</li>
<li class="fragment fade-up text-justify no-bullets" data-fragment-index="4" style="font-size: 26px;">
Calcule también la probabilidad de que <strong>exactamente 3 germinen</strong>.
</li>

</ul>
</div>

<div class="card fragment fade-up" data-fragment-index="5">
<ul>

<h4 class="fragment fade-in" data-fragment-index="7">Al menos una germina</h4>

<li class="fragment fade-up text-justify no-bullets" data-fragment-index="8" style="font-size: 24px;">
$P(\text{ninguna}) = (0.25)^4 = 0.0039$ (ninguna germina, todas fallan)
</li>
<li class="fragment fade-up no-bullets" data-fragment-index="9" style="font-size: 24px;">
$P(\geq 1) = 1 - 0.0039 = \mathbf{0.9961}$ (la probabilidad de que al menos una germine es el complemento de que ninguna germine)
</li>


<h4 class="fragment fade-in" data-fragment-index="10">Exactamente 3 germinan</h4> 

<li class="fragment fade-up text-justify no-bullets" data-fragment-index="11" style="font-size: 24px;">
Sea el caso específico: las primeras 3 germinan y la última no. La probabilidad de este caso es:
</li>
<li class="fragment fade-up text-justify no-bullets" data-fragment-index="12" style="font-size: 24px;">
$P(\text{una semilla no germina}) = (0.75)^3 \times (0.25) = 0.1055$
</li>
<li class="fragment fade-up text-justify no-bullets" data-fragment-index="13" style="font-size: 24px;">
Pero hay 4 formas de elegir cuál semilla no germina, por lo que:  
$P(\text{exactamente 3}) = 4 \times 0.1055 = \mathbf{0.422}$ 
</li> 

<li class="fragment fade-up text-justify no-bullets" data-fragment-index="14" style="font-size: 24px;">
Hay un 42.2% de probabilidad de que exactamente 3 de las 4 semillas germinen.
</li>
</ul>
</div>

</div>


