## Ejemplo 2: Ganancia de peso porcina criolla

<p class="fragment fade-up" data-fragment-index="0" style="font-size: 28px; text-align: justify; line-height: 1.2; margin-bottom: 6px;">
Un grupo de investigadores pecuarios desea verificar si el productividad promedio de cerdos criolla es menor a 18 kg por animal. En una muestra de $\small n=15$ granjas se obtuvo $\small \bar{x}=16.9$ con $\small s=2.4$ (desconocida) y $\small \alpha=0.05$. ¿Hay evidencia de que el productividad promedio es menor a 18 kg/animal?
</p>

<div style="display:grid; grid-template-columns:1fr 1fr; gap:10px; margin-top: 6px; align-items:start;">

<div class="fragment fade-up box-blue-accent" data-fragment-index="1" style="font-size: 24px;">
<strong class="text-block-blue">Paso 1. Hipótesis:</strong>
$$H_0:\mu\geq18 \qquad H_1:\mu<18$$
Prueba de cola izquierda.
</div>

<div class="fragment fade-up box-green-accent" data-fragment-index="2" style="font-size: 24px;">
<strong class="text-block-green">Paso 2. Estadístico:</strong>
Prueba $t$ de Student ($\sigma$ desconocida, $n$ pequeña):
$$t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}}=\frac{16.9-18}{2.4/\sqrt{15}}=-1.77$$
</div>

<div class="fragment fade-up box-blue-accent" data-fragment-index="3" style="font-size: 24px;">
<strong class="text-block-blue">Paso 3. Criterio de decisión:</strong>
Para $\alpha=0.05$ y $gl=14$, valor crítico $t_{0.05,14}=-1.761$.
$$t_{cal}=-1.77 < t_{crit}=-1.761 \;\Rightarrow\; \text{se rechaza } H_0$$
</div>

<div class="fragment fade-up box-green-accent" data-fragment-index="4" style="font-size: 24px;">
<strong class="text-block-green">Paso 4. Valor-p:</strong>
$$p=P(T<-1.77)\approx 0.049$$
$$p < 0.05 \;\Rightarrow\; \text{se rechaza } H_0$$
</div>

</div>

<div class="fragment fade-up" data-fragment-index="5"
style="background-color:#eef7ee; padding:8px; border-radius:12px; border-left:8px solid #1b4d2e; margin-top:8px;">
<div style="font-size:24px; text-align:justify; line-height:1.3; margin-top:4px;">
Aunque el valor-p es ligeramente menor que 0.05, existe evidencia para rechazar $H_0$ y concluir que el productividad promedio de cerdos criolla es menor a 18 kg/animal. Sin embargo, la evidencia es débil, pues el valor-p está muy cerca del nivel de significancia.
</div>
</div>

