## Modelo probabilístico de una variable

<div class="block-definition fragment fade-up" data-fragment-index="1">
<div class="block-title">Modelo probabilístico</div>
<div class="block-body">
Un modelo probabilístico describe el comportamiento aleatorio de una variable mediante una distribución de probabilidad.

$$
X \sim \text{Nombre}(\theta)
$$

donde $\theta$ representa los parámetros del modelo.

</div>
</div>
<p class="fragment fade-up text-justify" data-fragment-index="1" style="font-size: 28px;">
Algunos ejemplos de modelos probabilísticos comunes en biología y zootecnia son:
</p>
<ul >
<li class="fragment fade-up text-justify" data-fragment-index="2"
style="font-size: 25px;">
Modelo discreto con dos resultados posibles: vivo o muerto, sano o enfermo. Se representa como: $X \sim \text{Bernoulli}(p)$
</li>

<li class="fragment fade-up text-justify" data-fragment-index="3"style="font-size: 25px;">
Número de éxitos en $n$ ensayos. Se representa como:
$X \sim \text{Binomial}(n,p)$
</li>

<li class="fragment fade-up text-justify" data-fragment-index="4"
style="font-size: 26px;">
Conteo de eventos en un intervalo. Se representa como:
$X \sim \text{Poisson}(\lambda)$
</li>

<li class="fragment fade-up text-justify" data-fragment-index="5"style="font-size: 26px;">
Modelo continuo con forma de campana. Se representa como:
$X \sim \text{Normal}(\mu,\sigma^2)$
</li>

<li class="fragment fade-up text-justify" data-fragment-index="6"style="font-size: 26px;">
Modelo de tiempos de espera. Se representa como:
$X \sim \text{Exp}(\lambda)$
</li>
</ul>


