## Ejercicio: éxito de proyectos de inversión

<div class="twocol">

<div class="card fragment fade-up crispdm-card--gray" data-fragment-index="1">
<ul>
<li class="fragment fade-up" data-fragment-index="2" style="font-size: 26px; text-align: justify;list-style: none;">
Se siembran 4 proyectos de inversión de forma independiente. La probabilidad de éxito de cada proyecto es $p = 0.75$.
</li>
<li class="fragment fade-up" data-fragment-index="3" style="font-size: 26px; text-align: justify;list-style: none;">
Calcule la probabilidad de que <strong>al menos un proyecto tenga éxito</strong>.
</li>
<li class="fragment fade-up" data-fragment-index="4" style="font-size: 26px; text-align: justify;list-style: none;">
Calcule también la probabilidad de que <strong>exactamente 3 tengan éxito</strong>.
</li>

</ul>
</div>

<div class="card fragment fade-up crispdm-card--gray" data-fragment-index="5">
<ul>

<h4 class="fragment fade-in" data-fragment-index="7">Al menos una tiene éxito</h4>

<li class="fragment fade-up" data-fragment-index="8" style="font-size: 24px; text-align: justify;list-style: none;">
$P(\text{ninguna}) = (0.25)^4 = 0.0039$ (ninguna tiene éxito, todas fallan)
</li>
<li class="fragment fade-up" data-fragment-index="9" style="font-size: 24px; list-style: none;">
$P(\geq 1) = 1 - 0.0039 = \mathbf{0.9961}$ (la probabilidad de que al menos una tenga éxito es el complemento de que ninguna tenga éxito)
</li>


<h4 class="fragment fade-in" data-fragment-index="10">Exactamente 3 tienen éxito</h4> 

<li class="fragment fade-up" data-fragment-index="11" style="font-size: 24px; text-align: justify; list-style: none; ">
Sea el caso específico: las primeras 3 tienen éxito y la última no. La probabilidad de este caso es:
</li>
<li class="fragment fade-up" data-fragment-index="12" style="font-size: 24px; text-align: justify;list-style: none; ">
$P(\text{un proyecto no tiene éxito}) = (0.75)^3 \times (0.25) = 0.1055$
</li>
<li class="fragment fade-up" data-fragment-index="13" style="font-size: 24px; text-align: justify; list-style: none; ">
Pero hay 4 formas de elegir cuál proyecto no tiene éxito, por lo que:  
$P(\text{exactamente 3}) = 4 \times 0.1055 = \mathbf{0.422}$ 
</li> 

<li class="fragment fade-up" data-fragment-index="14" style="font-size: 24px; text-align: justify; list-style: none; ">
Hay un 42.2% de probabilidad de que exactamente 3 de las 4 proyectos tengan éxito.
</li>
</ul>
</div>

</div>


