## Ejemplo 2

<div class="twocol">

<div class="card fragment fade-up" data-fragment-index="1">
<p>
CV para comparación de muestras
</p>
<ul>
<li class="fragment fade-up text-justify" data-fragment-index="3" style="font-size: 22px;">
Se comparan los tiempos de entrega (minutos) de dos empresas de mensajería, de cada empresa se tomó una muestra de datos.
</li>

<li class="fragment fade-up text-justify" data-fragment-index="4" style="font-size: 22px;">
Determinar cual de las dos empresas es mejor usando el coeficiente de variación.
</li>
<li class="fragment fade-up text-justify" data-fragment-index="5" style="font-size: 22px;">
Empresa A
</li>
<li class="fragment fade-up text-justify" data-fragment-index="6" style="font-size: 22px;">
Datos:
</li>
<li class="fragment fade-up text-justify" data-fragment-index="7" style="font-size: 22px;">
Media: $\bar{x}_A=20\,minutos$
</li>
<li class="fragment fade-up text-justify" data-fragment-index="8" style="font-size: 22px;">
Desviación Estandar: $s_A=1,58$
</li>
<li class="fragment fade-up text-justify" data-fragment-index="9" style="font-size: 22px;">
Empresa B
</li>
</li>
<li class="fragment fade-up text-justify" data-fragment-index="10" style="font-size: 22px;">
Datos:
</li>
<li class="fragment fade-up text-justify" data-fragment-index="11" style="font-size: 22px;">
Media: $\bar{x}_B=38\,minutos$
</li>
<li class="fragment fade-up text-justify" data-fragment-index="12" style="font-size: 22px;">
Desviación Estandar: $s_B=10,37$
</li>

</ul>
</div>

<div class="card fragment fade-up" data-fragment-index="13">
<ul>
<li class="fragment fade-up text-justify" data-fragment-index="14" style="font-size: 22px;">
Se procede a hallar los dos coeficientes de variación, no es necesario colocar valor absoluto ya que ambas medias son positivas.
</li>

<li class="fragment fade-in text-justify" data-fragment-index="15" style="font-size: 22px;">
$CV_A=\frac{s_A}{\bar{x}_A}\cdot 100\%=\frac{1,58}{20}\cdot 100\%=7,9\%$
</li>

<li class="fragment fade-in text-justify" data-fragment-index="16" style="font-size: 22px;">
$CV_B=\frac{s_B}{\bar{x}_B}\cdot 100\%=\frac{10,37}{38}\cdot 100\%=27,29\%$
</li>
<li class="fragment fade-in text-justify" data-fragment-index="17" style="font-size: 22px;">
Comparando los dos CV, se tiene que:
</li>
<li class="fragment fade-in text-justify" data-fragment-index="18" style="font-size: 22px;">
La empresa A es preferible porque no solo presenta menor tiempo promedio de entrega, sino también menor variabilidad, lo que garantiza un servicio más rápido y consistente.
</li>

</ul>
</div>
</div>

