## Ejemplos
<div class="twocol">

<div class="card fragment fade-up" data-fragment-index="1">
<p class="fragment fade-up" data-fragment-index="2" style="font-size: 30px; text-align: justify;">
Datos sin agrupar
</p>

<p class="fragment fade-up" data-fragment-index="3" style="font-size: 20px; text-align: justify;">
Se tienen los siguientes datos: 6, 10, 12, 3, 5, 14, 15, 17, 18, 7, 8, 9, 20, 21, 22. Vamos hallar los cuartiles del anterior conjunto de datos.
</p>

<ol>
<li class="fragment fade-up" data-fragment-index="4" style="font-size: 20px; text-align: justify;">
Primero se ordenan los datos en orden ascendente: 3, 5, 6, 7, 8, 9, 10, 12, 14, 15, 17, 18, 20, 21, 22
</li>
<li class="fragment fade-up" data-fragment-index="9" style="font-size: 20px; text-align: justify;">
Aplicamos la formula:
$$Q_k = \frac{k(n+1)}{4}$$
</li>
<li class="fragment fade-up" data-fragment-index="12" style="font-size: 20px; text-align: justify;">
Para el cuartil 1 se tiene que $n=15$ y $k=1$ , reemplazando se tiene que:
$$Q_1 = \frac{1\cdot (15+1)}{4}=\frac{16}{4}=4$$
</li>
<li class="fragment fade-up" data-fragment-index="13" style="font-size: 20px; text-align: justify;">
Con $Q_1=4$ se busca el valor correspondiente a la posición 4 en los datos ordenados. El valor que corresponde a esa posición es: $x_4 = 7$ y por lo tanto el $Q_1=7$.
</li>
</ol>
</div>

<div class="card fragment fade-up" data-fragment-index="14">

<ul>
<li class="fragment fade-in" data-fragment-index="17" style="font-size: 20px; text-align: justify;">
Ahora para el cuartil 2 (mediana)
<ol>
<li class="fragment fade-in" data-fragment-index="18" style="font-size: 20px; text-align: justify;">
$n=15$ y $k=2$ , Reemplazando:
</li>
<li class="fragment fade-in" data-fragment-index="19" style="font-size: 20px; text-align: justify;">
$Q_2 = \frac{2\cdot (15+1)}{4}=\frac{2\cdot (16)}{4}=\frac{32}{4}=8$
</li>
<li class="fragment fade-in" data-fragment-index="20" style="font-size: 20px; text-align: justify;">
$Q_2=8$, el dato correspondiente a la posición 8 es: $x_8=12$ y por lo tanto el $Q_2=12$.
</li>
</ol>
</li>

<li class="fragment fade-in" data-fragment-index="21" style="font-size: 20px; text-align: justify;">
Ahora para el cuartil 3
<ol>
<li class="fragment fade-in" data-fragment-index="22" style="font-size: 20px; text-align: justify;">
$n=15$ y $k=3$ , Reemplazando:
</li>

<li class="fragment fade-in" data-fragment-index="23" style="font-size: 20px; text-align: justify;">
$Q_3 = \frac{3\cdot (15+1)}{4}=\frac{3\cdot (16)}{4}=\frac{48}{4}=12$
</li>

<li class="fragment fade-in" data-fragment-index="24" style="font-size: 20px; text-align: justify;">
$Q_3=12$, el dato correspondiente a la posición 12 es: $x_{12}=18$ y por lo tanto el $Q_3=18$.
</li>

</ol>
</li>
<li class="fragment fade-in" data-fragment-index="24" style="font-size: 20px; text-align: justify;">
Interpretación:
</li>

<li class="fragment fade-in" data-fragment-index="25" style="font-size: 20px; text-align: justify;">
El 25% de los datos está por debajo de 7
</li>

<li class="fragment fade-in" data-fragment-index="26" style="font-size: 20px; text-align: justify;">
El 50% está por debajo de 12
</li>

<li class="fragment fade-in" data-fragment-index="27" style="font-size: 20px; text-align: justify;">
El 75% está por debajo de 18
</li>

</ul>
</div>
</div>

