## Soporte de una variable aleatoria

<div class="block-definition fragment fade-up" data-fragment-index="1">
  <div class="block-title">Definición: Soporte</div>
  <div class="block-body style=font-size: 30px; text-align: justify;">
El <strong>soporte</strong> de una variable aleatoria $X$ es el conjunto de valores $x$ donde $P(X = x) > 0$ (discreta) o $f(x) > 0$ (continua).
  </div>
</div>
<ul style="margin-top: 20px;">
<li class="fragment fade-up" data-fragment-index="2" style="font-size: 28px; text-align: justify;">
El soporte define el <em>rango natural</em> de la variable: los valores que realmente pueden ocurrir.
</li>
<li class="fragment fade-up" data-fragment-index="3" style="font-size: 28px; text-align: justify;">
Por ejemplo: número de parásitos en sangre $\Rightarrow$ soporte $\{0,1,2,\ldots\}$; temperatura corporal $\Rightarrow$ soporte $(35, 45)$ °C (en la práctica clínica).
</li>
</ul>
<h4 class="fragment fade-up" data-fragment-index="4" style="font-size: 28px; text-align: justify;">
Variables Aleatorias Mixtas
</h4>
<div class="block-note fragment fade-up" data-fragment-index="5">
  <div class="block-body">
<p>
Existen variables que son <strong>ni puramente discretas ni puramente continuas</strong>. Por ejemplo: el tiempo de supervivencia en un estudio cuando algunos pacientes no presentan el evento (se "censuran").
</p>
  </div>
</div>

<ul style="margin-top: 20px;">
<li class="fragment fade-up" data-fragment-index="6" style="font-size: 28px; text-align: justify;">
Estas variables tienen una FDA con <em>saltos</em> en ciertos puntos y regiones <em>continuas</em> en otros.
</li>
<li class="fragment fade-up" data-fragment-index="7" style="font-size: 28px; text-align: justify;">
En este curso nos concentraremos en los dos tipos puros: discreto y continuo.
</li>
</ul>

