## Contenido


<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 42px; margin-top: 20px; font-size: 28px; align-items: start;line-height:1.2;">

<div>

<h3 class="fragment fade-in" data-fragment-index="1"
style="font-size: 30px; margin-bottom: 14px; color: #1b4d2e;">
Parte I: Pruebas de hipótesis para la diferencia de medias.
</h3>

<ul>
<li class="fragment fade-in" data-fragment-index="2">
Introducción a la comparación de dos poblaciones.
</li>

<li class="fragment fade-in" data-fragment-index="3">
Tipos de muestras y planteamiento de hipótesis.
</li>

<li class="fragment fade-in" data-fragment-index="4">
Selección del estadístico de prueba.
</li>

<li class="fragment fade-in" data-fragment-index="5">
Pruebas para la diferencia de medias.
</li>

<li class="fragment fade-in" data-fragment-index="6">
Criterios de decisión.
</li>
<li class="fragment fade-in" data-fragment-index="7">
Ejemplos resueltos.
</li>
</ul>

</div>

<div>

<h3 class="fragment fade-in" data-fragment-index="8"
style="font-size: 30px; margin-bottom: 14px; color: #1a3a6b;">
Parte II: Pruebas de hipótesis para la diferencia de proporciones
</h3>

<ul>
<li class="fragment fade-in" data-fragment-index="9">
Diferencia de proporciones.
</li>

<li class="fragment fade-in" data-fragment-index="10">
Hipótesis para diferencia de proporciones
</li>

<li class="fragment fade-in" data-fragment-index="11">
Estadístico de prueba para diferencia de proporciones.
</li>

<li class="fragment fade-in" data-fragment-index="12">
Criterios de decisión.
</li>

<li class="fragment fade-in" data-fragment-index="13">
Ejemplos resueltos.
</li>

</ul>
</div>

<div>
<h3 class="fragment fade-in" data-fragment-index="14"
style="font-size: 30px; margin-bottom: 14px; color: #79260d;">
Parte III: Errores, potencia y razón de varianzas.
</h3>

<ul>
<li class="fragment fade-in" data-fragment-index="15">
Error tipo I y error tipo II.
</li>

<li class="fragment fade-in" data-fragment-index="16">
Tabla de decisiones y relación entre $\small \alpha$ y $\small \beta$.
</li>

<li class="fragment fade-in" data-fragment-index="17">
Potencia estadística y función de potencia.
</li>

<li class="fragment fade-in" data-fragment-index="18">
Efecto del tamaño de muestra sobre la potencia.
</li>

<li class="fragment fade-in" data-fragment-index="19">
Determinación del tamaño de muestra.
</li>

<li class="fragment fade-in" data-fragment-index="20">
Prueba de hipótesis para la razón de varianzas (distribución $\small F$).
</li>

<li class="fragment fade-in" data-fragment-index="21">
Ejemplo y solución.
</li>

<li class="fragment fade-in" data-fragment-index="22">
Taller en clase.
</li>
</ul>
</div>
</div>


